default_stages:
  - commit
fail_fast: true
exclude: ^app/.envs/.local/
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args:
          - "--maxkb=500"
          - "--enforce-all"
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args:
          - "--remove"
      - id: forbid-new-submodules
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"
  - repo: "https://github.com/psf/black"
    rev: 24.10.0
    hooks:
      - id: black
        exclude: ^.*migrations/


  - repo: "https://github.com/timothycrosley/isort"
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: "https://github.com/PyCQA/flake8"
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - "--config=setup.cfg"
        additional_dependencies:
          - flake8-isort
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
