version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: "backend"
    volumes:
      - .:/app
    environment:
      - PORT=8000
    ports:
    - 8000:8000
